"""Initial migration

Revision ID: bbde991390f3
Revises: 7a82d0fc0ed0
Create Date: 2023-10-24 13:18:52.387716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbde991390f3'
down_revision = '7a82d0fc0ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('covers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=250), nullable=False))
        batch_op.drop_column('file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('covers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', mysql.VARCHAR(length=250), nullable=False))
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
